packages:
  - 'apps/*'
  - 'apps/desktop/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  typescript: ^6.0.3
  react: ^19.2.6
  react-dom: ^19.2.6
  next: ^16.2.6
  playwright: ^1.59.1
  '@biomejs/biome': ^2.4.14

allowBuilds:
  core-js: true
  protobufjs: true
